version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}whatsapp-front-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: local-stage
    ports:
      - "8080:8080"
    command: /bin/sh -c "npm i && quasar dev -m spa"
